### ISSUE TITLE
[QUERY] How is it different from Web Voyager

### ISSUE THREAD

**Issue by andr0s** [EmergenceAI/Agent-E#117]
Can you guys briefly explain 

1. How is this project different from Web Voyager?

2. The main question - the overall principle of work. I don't see anything like that in the long readme, only what it can do, and the installation instructions. Does it use AI-based interface elements recognition to match them with the actual HTML code to emulate clicks, keyboard presses etc.? Adding just a few sentences would be very useful

Thanks!

**Comment by bolt163** [comment]
talk is cheap, code is there

**Comment by andr0s** [comment]
> talk is cheap, code is there

yeah why even bother writing docs, people just wasting their time innit?

facepalm.jpg

**Comment by deepak-akkil** [comment]
Hey
Feedback noted on improving readme.
You can read a lot more about how Agent-E works in our paper (also linked in the readme).

https://arxiv.org/abs/2407.13032

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by andr0s** [comment]
@deepak-akkil yeah thanks. I actually finally read through the readme and found the answers. Apparently you guys aren't doing the visual analysis of the image which has pros and cons but in my specific case it's a huge pro because it doesn't get extremely expensive

**Comment by teaxio** [comment]
> @deepak-akkil yeah thanks. I actually finally read through the readme and found the answers. Apparently you guys aren't doing the visual analysis of the page which has pros and cons but in my specific case it's a huge pro because it doesn't get extremely expensive

Exactly @andr0s There is a place for vision and a place for DOM. Each has pros and cons. I think the answer lies in a blend of the two approaches. Feel free to experiment and let us know. If you have specific suggestions on the readme, please open a PR and we will be happy to take a look (or hit us up on Discord link in the repo).
