### ISSUE TITLE
[BUG] Agents being stuck at Aync Function indefinetly 

### ISSUE THREAD

**Issue by krishnashed** [EmergenceAI/Agent-E#29]
### Title
Agent stuck at while performing tasks

### Description
Agent gets stuck for long time, without any response in the browser chat and terminal,

![image](https://github.com/EmergenceAI/Agent-E/assets/60742358/646663e6-2d31-4d05-b597-21918b33fcde)

### Steps to Reproduce
1.  Run Agent-E using python -u -m ae.main
2. Prompt "find total number of job openings at Disney"
3. Further prompting "I want to know the total number of jobs, not just the number of pages, so please go through each of these pages, and tell me the total number of jobs at Disney"

### Expected Behavior
Navigating through each page of Job posting at Disney, and giving in the details one after another, then once scrapping all pages is done, giving the final number

### Actual Behavior
Agent is just stuck with 
![image](https://github.com/EmergenceAI/Agent-E/assets/60742358/6641e729-69a9-4935-bbd9-a67e96ce90aa)
![image](https://github.com/EmergenceAI/Agent-E/assets/60742358/6e0c41c5-3fc2-4871-9355-35776551c947)

### Environment
- OS: ubuntu in WSL2
- Browser chromium with playwrite

**Comment by teaxio** [comment]
@krishnashed I tried this a few times. The prompts that you are showing, it is not a loop, rather the agent is asking for your input. The bigger question is why. atm it is not able to do pagination. This is one of the areas we would like to improve the agent in. What is interesting is that it tried to calculate number of jobs per page times number of pages. I do not know where it got 20 jobs from when the page has 15. It was interesting to see it attempt that computation over going from page to page. There are other times I have seen it call out 15 jobs per page:
```
The total number of job openings at Disney is 1,215 (15 jobs per page across 81 pages).
```

**Comment by teaxio** [comment]
Closing this since there was no response. Please reopen if you are still facing this issue or ping on Discord.
