### ISSUE TITLE
[BUG] Windows 10 prompts that Chrome cannot be found after executing the command

### ISSUE THREAD

**Issue by haige268** [EmergenceAI/Agent-E#59]
![image](https://github.com/EmergenceAI/Agent-E/assets/35056930/291e53bc-c35b-4e10-9300-97748c790063)
![image](https://github.com/EmergenceAI/Agent-E/assets/35056930/d4717ce1-2b97-4e2c-9902-2d80a03da4d1)
![image](https://github.com/EmergenceAI/Agent-E/assets/35056930/98109de3-98e3-41ee-8086-dcf4ca7b9cd7)
I'm a Windows10 computer, and it's configured according to the requirements, but when it runs, it is an error that I can't find chrome, please look at my screenshot, where am I misconfigured? Or is it because the app itself has a problem with Windows 10 compatibility?

**Comment by teaxio** [comment]
@haige268 thank you for trying this out. Have you tried installing playwright from the steps in the readme? Before I try to dig deeper I wonder if that will help it?

**Comment by deepak-akkil** [comment]
Hi @haige268 . There are no known compatibility issues with Windows 10. A big difference I see in your screenshot is "chrome-beta" being the browser type. Playwright has slightly different way of initializing chrome Vs chrome-beta, and today we only support chrome (though it is very easy to make it work with chrome beta or even msedge) . We will make this browser type an env variable in the next release 
In the meanwhile, you can try the following two options:
a) install playwright chrome and do not set the browser_storage_dir to point to that chrome instance. 
b) change the value "chrome" set as browser type in playwright_manager.py to "chrome-beta" in the line  playwright.chromium().launch

**Comment by teaxio** [comment]
Closing this issue since we have not heard back. Please feel free to reopen if you still need help or ping on Discord.
