### ISSUE TITLE
能运行但是没反应[BUG] 

### ISSUE THREAD

**Issue by luaonze** [EmergenceAI/Agent-E#76]
It works but it doesn't respond and my interface is different from others
<img width="392" alt="截屏2024-07-06 00 23 41" src="https://github.com/EmergenceAI/Agent-E/assets/102591430/7583fbd7-ce1e-41b2-827e-a5a4dfded70c">
After I run llama3 with ollama locally, I open the page like the screenshot, which is completely different from others. I don't know what to do. I have found many request methods, but they are all wrong.<img width="1204" alt="截屏2024-07-06 00 25 36" src="https://github.com/EmergenceAI/Agent-E/assets/102591430/287da156-58e4-4ad1-a384-e77d785b0f5e">
There is nothing wrong with my running command. I don't know where the problem is. This problem has troubled me for 3 days. Please help me. I give you my most sincere thanks.

**Comment by teaxio** [comment]
@luaonze we have noticed that when using ollama that all the details related to function calling are gone. Meaning ollama drops them before they reach the intended LLM. There is a section in our readme that shows how to setup ollama correctly. Have you tried it?
However, even with that there is limited success I suspect due to the verbosity of the planner. We are in need for community members to help us make this work with local LLMs. We have not had time to free up cycles for it :( 
Please let me know about the above question

**Comment by teaxio** [comment]
Once you do set this up successfully, I suspect that you will run into this #75 
As indicated in the other bug, I welcome ideas on how to defeat this.

**Comment by luaonze** [comment]
我试过了ollama 但是我的界面也和其他人不太一样 尤其是那个机器人小图标 和别人的完全不同,我在我本地去提问 好想他是没有反应的

**Comment by luaonze** [comment]
而且 我看你你发我的解决办法 但是我让他操作 那个模型是不回我的,他没有任何反应,我卸载重装了很多次 但还是没用

**Comment by luaonze** [comment]
I tried ollama, and my interface is the same as others, especially the robot icon is completely different. I asked questions locally, but there seems to be no response.

And I saw you sent me the solution, but I asked him to operate the model but he didn't reply to me. He didn't respond at all. I uninstalled and reinstalled many times but it still didn't work.

**Comment by teaxio** [comment]
So you have a problem with Ollama setup then @luaonze ? If that's the case, there is not much I can do

**Comment by luaonze** [comment]
I think it might be, but I deployed it on several computers and got the same result.

**Comment by luaonze** [comment]
I think my model is not running. The llama3 model in ollama in docker that I use may not be running.

**Comment by liuyanmei22** [comment]
@luaonze 你好，请问这个问题后面解决了吗？

**Comment by bolt163** [comment]
这个Agent不支持开源类未实现函数调用的llm...
