### ISSUE TITLE
这Agent压根就不支持开源模型，为何要在文档里说支持开源模型误导人？？？

### ISSUE THREAD

**Issue by bolt163** [EmergenceAI/Agent-E#86]
### Title
[Short description of the query]
as title description, it's nearly cheating[坑!!]
### Description
Please provide a detailed description of your question or general query.

### Additional Context
Add any other context or information that could help in addressing your query.

**Comment by teaxio** [comment]
Sorry I have no idea what the question here is. Please fill out the template and post this in English if you do not mind. I will close this for now
